/// (Hindi name, English name) for every Indian state/UT. The dropdown
/// value stored/matched against is the Hindi name (unchanged from before
/// this became bilingual, so existing saved profiles keep working) - only
/// the displayed label switches with the language toggle.
const List<(String, String)> kIndianStates = [
  ('आंध्र प्रदेश', 'Andhra Pradesh'),
  ('अरुणाचल प्रदेश', 'Arunachal Pradesh'),
  ('असम', 'Assam'),
  ('बिहार', 'Bihar'),
  ('छत्तीसगढ़', 'Chhattisgarh'),
  ('गोवा', 'Goa'),
  ('गुजरात', 'Gujarat'),
  ('हरियाणा', 'Haryana'),
  ('हिमाचल प्रदेश', 'Himachal Pradesh'),
  ('झारखंड', 'Jharkhand'),
  ('कर्नाटक', 'Karnataka'),
  ('केरल', 'Kerala'),
  ('मध्य प्रदेश', 'Madhya Pradesh'),
  ('महाराष्ट्र', 'Maharashtra'),
  ('मणिपुर', 'Manipur'),
  ('मेघालय', 'Meghalaya'),
  ('मिज़ोरम', 'Mizoram'),
  ('नागालैंड', 'Nagaland'),
  ('ओडिशा', 'Odisha'),
  ('पंजाब', 'Punjab'),
  ('राजस्थान', 'Rajasthan'),
  ('सिक्किम', 'Sikkim'),
  ('तमिलनाडु', 'Tamil Nadu'),
  ('तेलंगाना', 'Telangana'),
  ('त्रिपुरा', 'Tripura'),
  ('उत्तर प्रदेश', 'Uttar Pradesh'),
  ('उत्तराखंड', 'Uttarakhand'),
  ('पश्चिम बंगाल', 'West Bengal'),
  ('अंडमान व निकोबार', 'Andaman & Nicobar'),
  ('चंडीगढ़', 'Chandigarh'),
  ('दादरा व नगर हवेली', 'Dadra & Nagar Haveli'),
  ('दमन व दीव', 'Daman & Diu'),
  ('दिल्ली', 'Delhi'),
  ('जम्मू और कश्मीर', 'Jammu & Kashmir'),
  ('लद्दाख', 'Ladakh'),
  ('लक्षद्वीप', 'Lakshadweep'),
  ('पुदुच्चेरी', 'Puducherry'),
];
